// this file is @generated
use std::fmt;

use serde::{Deserialize, Deserializer, Serialize, Serializer};

#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[non_exhaustive]
pub enum Currency {
    Aed,
    Afn,
    All,
    Amd,
    Ang,
    Aoa,
    Ars,
    Aud,
    Awg,
    Azn,
    Bam,
    Bbd,
    Bdt,
    Bgn,
    Bhd,
    Bif,
    Bmd,
    Bnd,
    Bob,
    Brl,
    Bsd,
    Btn,
    Bwp,
    Byn,
    Bzd,
    Cad,
    Cdf,
    Chf,
    Clp,
    Cnh,
    Cny,
    Cop,
    Crc,
    Cuc,
    Cup,
    Cve,
    Czk,
    Djf,
    Dkk,
    Dop,
    Dzd,
    Egp,
    Ern,
    Etb,
    Eur,
    Fjd,
    Fkp,
    Gbp,
    Gel,
    Ghs,
    Gip,
    Gmd,
    Gnf,
    Gtq,
    Gyd,
    Hkd,
    Hnl,
    Hrk,
    Htg,
    Huf,
    Idr,
    Ils,
    Inr,
    Iqd,
    Irr,
    Isk,
    Jmd,
    Jod,
    Jpy,
    Kes,
    Kgs,
    Khr,
    Kmf,
    Kpw,
    Krw,
    Kwd,
    Kyd,
    Kzt,
    Lak,
    Lbp,
    Lkr,
    Lrd,
    Lsl,
    Lyd,
    Mad,
    Mdl,
    Mga,
    Mkd,
    Mmk,
    Mnt,
    Mop,
    Mru,
    Mur,
    Mvr,
    Mwk,
    Mxn,
    Myr,
    Mzn,
    Nad,
    Ngn,
    Nio,
    Nok,
    Npr,
    Nzd,
    Omr,
    Pab,
    Pen,
    Pgk,
    Php,
    Pkr,
    Pln,
    Pyg,
    Qar,
    Ron,
    Rsd,
    Rub,
    Rwf,
    Sar,
    Sbd,
    Scr,
    Sdg,
    Sek,
    Sgd,
    Shp,
    Sll,
    Sos,
    Srd,
    Ssp,
    Std,
    Stn,
    Svc,
    Syp,
    Szl,
    Thb,
    Tjs,
    Tmt,
    Tnd,
    Top,
    Try,
    Ttd,
    Twd,
    Tzs,
    Uah,
    Ugx,
    Usd,
    Uyu,
    Uzs,
    Ves,
    Vnd,
    Vuv,
    Wst,
    Xaf,
    Xcd,
    Xof,
    Xpf,
    Yer,
    Zar,
    Zmw,
    Zwl,
    /// A value this version of the SDK does not know yet.
    Unknown(String),
}

impl Currency {
    /// The value as sent on the wire.
    #[must_use]
    pub fn as_str(&self) -> &str {
        match self {
            Self::Aed => "AED",
            Self::Afn => "AFN",
            Self::All => "ALL",
            Self::Amd => "AMD",
            Self::Ang => "ANG",
            Self::Aoa => "AOA",
            Self::Ars => "ARS",
            Self::Aud => "AUD",
            Self::Awg => "AWG",
            Self::Azn => "AZN",
            Self::Bam => "BAM",
            Self::Bbd => "BBD",
            Self::Bdt => "BDT",
            Self::Bgn => "BGN",
            Self::Bhd => "BHD",
            Self::Bif => "BIF",
            Self::Bmd => "BMD",
            Self::Bnd => "BND",
            Self::Bob => "BOB",
            Self::Brl => "BRL",
            Self::Bsd => "BSD",
            Self::Btn => "BTN",
            Self::Bwp => "BWP",
            Self::Byn => "BYN",
            Self::Bzd => "BZD",
            Self::Cad => "CAD",
            Self::Cdf => "CDF",
            Self::Chf => "CHF",
            Self::Clp => "CLP",
            Self::Cnh => "CNH",
            Self::Cny => "CNY",
            Self::Cop => "COP",
            Self::Crc => "CRC",
            Self::Cuc => "CUC",
            Self::Cup => "CUP",
            Self::Cve => "CVE",
            Self::Czk => "CZK",
            Self::Djf => "DJF",
            Self::Dkk => "DKK",
            Self::Dop => "DOP",
            Self::Dzd => "DZD",
            Self::Egp => "EGP",
            Self::Ern => "ERN",
            Self::Etb => "ETB",
            Self::Eur => "EUR",
            Self::Fjd => "FJD",
            Self::Fkp => "FKP",
            Self::Gbp => "GBP",
            Self::Gel => "GEL",
            Self::Ghs => "GHS",
            Self::Gip => "GIP",
            Self::Gmd => "GMD",
            Self::Gnf => "GNF",
            Self::Gtq => "GTQ",
            Self::Gyd => "GYD",
            Self::Hkd => "HKD",
            Self::Hnl => "HNL",
            Self::Hrk => "HRK",
            Self::Htg => "HTG",
            Self::Huf => "HUF",
            Self::Idr => "IDR",
            Self::Ils => "ILS",
            Self::Inr => "INR",
            Self::Iqd => "IQD",
            Self::Irr => "IRR",
            Self::Isk => "ISK",
            Self::Jmd => "JMD",
            Self::Jod => "JOD",
            Self::Jpy => "JPY",
            Self::Kes => "KES",
            Self::Kgs => "KGS",
            Self::Khr => "KHR",
            Self::Kmf => "KMF",
            Self::Kpw => "KPW",
            Self::Krw => "KRW",
            Self::Kwd => "KWD",
            Self::Kyd => "KYD",
            Self::Kzt => "KZT",
            Self::Lak => "LAK",
            Self::Lbp => "LBP",
            Self::Lkr => "LKR",
            Self::Lrd => "LRD",
            Self::Lsl => "LSL",
            Self::Lyd => "LYD",
            Self::Mad => "MAD",
            Self::Mdl => "MDL",
            Self::Mga => "MGA",
            Self::Mkd => "MKD",
            Self::Mmk => "MMK",
            Self::Mnt => "MNT",
            Self::Mop => "MOP",
            Self::Mru => "MRU",
            Self::Mur => "MUR",
            Self::Mvr => "MVR",
            Self::Mwk => "MWK",
            Self::Mxn => "MXN",
            Self::Myr => "MYR",
            Self::Mzn => "MZN",
            Self::Nad => "NAD",
            Self::Ngn => "NGN",
            Self::Nio => "NIO",
            Self::Nok => "NOK",
            Self::Npr => "NPR",
            Self::Nzd => "NZD",
            Self::Omr => "OMR",
            Self::Pab => "PAB",
            Self::Pen => "PEN",
            Self::Pgk => "PGK",
            Self::Php => "PHP",
            Self::Pkr => "PKR",
            Self::Pln => "PLN",
            Self::Pyg => "PYG",
            Self::Qar => "QAR",
            Self::Ron => "RON",
            Self::Rsd => "RSD",
            Self::Rub => "RUB",
            Self::Rwf => "RWF",
            Self::Sar => "SAR",
            Self::Sbd => "SBD",
            Self::Scr => "SCR",
            Self::Sdg => "SDG",
            Self::Sek => "SEK",
            Self::Sgd => "SGD",
            Self::Shp => "SHP",
            Self::Sll => "SLL",
            Self::Sos => "SOS",
            Self::Srd => "SRD",
            Self::Ssp => "SSP",
            Self::Std => "STD",
            Self::Stn => "STN",
            Self::Svc => "SVC",
            Self::Syp => "SYP",
            Self::Szl => "SZL",
            Self::Thb => "THB",
            Self::Tjs => "TJS",
            Self::Tmt => "TMT",
            Self::Tnd => "TND",
            Self::Top => "TOP",
            Self::Try => "TRY",
            Self::Ttd => "TTD",
            Self::Twd => "TWD",
            Self::Tzs => "TZS",
            Self::Uah => "UAH",
            Self::Ugx => "UGX",
            Self::Usd => "USD",
            Self::Uyu => "UYU",
            Self::Uzs => "UZS",
            Self::Ves => "VES",
            Self::Vnd => "VND",
            Self::Vuv => "VUV",
            Self::Wst => "WST",
            Self::Xaf => "XAF",
            Self::Xcd => "XCD",
            Self::Xof => "XOF",
            Self::Xpf => "XPF",
            Self::Yer => "YER",
            Self::Zar => "ZAR",
            Self::Zmw => "ZMW",
            Self::Zwl => "ZWL",
            Self::Unknown(value) => value,
        }
    }
}

impl From<&str> for Currency {
    fn from(value: &str) -> Self {
        match value {
            "AED" => Self::Aed,
            "AFN" => Self::Afn,
            "ALL" => Self::All,
            "AMD" => Self::Amd,
            "ANG" => Self::Ang,
            "AOA" => Self::Aoa,
            "ARS" => Self::Ars,
            "AUD" => Self::Aud,
            "AWG" => Self::Awg,
            "AZN" => Self::Azn,
            "BAM" => Self::Bam,
            "BBD" => Self::Bbd,
            "BDT" => Self::Bdt,
            "BGN" => Self::Bgn,
            "BHD" => Self::Bhd,
            "BIF" => Self::Bif,
            "BMD" => Self::Bmd,
            "BND" => Self::Bnd,
            "BOB" => Self::Bob,
            "BRL" => Self::Brl,
            "BSD" => Self::Bsd,
            "BTN" => Self::Btn,
            "BWP" => Self::Bwp,
            "BYN" => Self::Byn,
            "BZD" => Self::Bzd,
            "CAD" => Self::Cad,
            "CDF" => Self::Cdf,
            "CHF" => Self::Chf,
            "CLP" => Self::Clp,
            "CNH" => Self::Cnh,
            "CNY" => Self::Cny,
            "COP" => Self::Cop,
            "CRC" => Self::Crc,
            "CUC" => Self::Cuc,
            "CUP" => Self::Cup,
            "CVE" => Self::Cve,
            "CZK" => Self::Czk,
            "DJF" => Self::Djf,
            "DKK" => Self::Dkk,
            "DOP" => Self::Dop,
            "DZD" => Self::Dzd,
            "EGP" => Self::Egp,
            "ERN" => Self::Ern,
            "ETB" => Self::Etb,
            "EUR" => Self::Eur,
            "FJD" => Self::Fjd,
            "FKP" => Self::Fkp,
            "GBP" => Self::Gbp,
            "GEL" => Self::Gel,
            "GHS" => Self::Ghs,
            "GIP" => Self::Gip,
            "GMD" => Self::Gmd,
            "GNF" => Self::Gnf,
            "GTQ" => Self::Gtq,
            "GYD" => Self::Gyd,
            "HKD" => Self::Hkd,
            "HNL" => Self::Hnl,
            "HRK" => Self::Hrk,
            "HTG" => Self::Htg,
            "HUF" => Self::Huf,
            "IDR" => Self::Idr,
            "ILS" => Self::Ils,
            "INR" => Self::Inr,
            "IQD" => Self::Iqd,
            "IRR" => Self::Irr,
            "ISK" => Self::Isk,
            "JMD" => Self::Jmd,
            "JOD" => Self::Jod,
            "JPY" => Self::Jpy,
            "KES" => Self::Kes,
            "KGS" => Self::Kgs,
            "KHR" => Self::Khr,
            "KMF" => Self::Kmf,
            "KPW" => Self::Kpw,
            "KRW" => Self::Krw,
            "KWD" => Self::Kwd,
            "KYD" => Self::Kyd,
            "KZT" => Self::Kzt,
            "LAK" => Self::Lak,
            "LBP" => Self::Lbp,
            "LKR" => Self::Lkr,
            "LRD" => Self::Lrd,
            "LSL" => Self::Lsl,
            "LYD" => Self::Lyd,
            "MAD" => Self::Mad,
            "MDL" => Self::Mdl,
            "MGA" => Self::Mga,
            "MKD" => Self::Mkd,
            "MMK" => Self::Mmk,
            "MNT" => Self::Mnt,
            "MOP" => Self::Mop,
            "MRU" => Self::Mru,
            "MUR" => Self::Mur,
            "MVR" => Self::Mvr,
            "MWK" => Self::Mwk,
            "MXN" => Self::Mxn,
            "MYR" => Self::Myr,
            "MZN" => Self::Mzn,
            "NAD" => Self::Nad,
            "NGN" => Self::Ngn,
            "NIO" => Self::Nio,
            "NOK" => Self::Nok,
            "NPR" => Self::Npr,
            "NZD" => Self::Nzd,
            "OMR" => Self::Omr,
            "PAB" => Self::Pab,
            "PEN" => Self::Pen,
            "PGK" => Self::Pgk,
            "PHP" => Self::Php,
            "PKR" => Self::Pkr,
            "PLN" => Self::Pln,
            "PYG" => Self::Pyg,
            "QAR" => Self::Qar,
            "RON" => Self::Ron,
            "RSD" => Self::Rsd,
            "RUB" => Self::Rub,
            "RWF" => Self::Rwf,
            "SAR" => Self::Sar,
            "SBD" => Self::Sbd,
            "SCR" => Self::Scr,
            "SDG" => Self::Sdg,
            "SEK" => Self::Sek,
            "SGD" => Self::Sgd,
            "SHP" => Self::Shp,
            "SLL" => Self::Sll,
            "SOS" => Self::Sos,
            "SRD" => Self::Srd,
            "SSP" => Self::Ssp,
            "STD" => Self::Std,
            "STN" => Self::Stn,
            "SVC" => Self::Svc,
            "SYP" => Self::Syp,
            "SZL" => Self::Szl,
            "THB" => Self::Thb,
            "TJS" => Self::Tjs,
            "TMT" => Self::Tmt,
            "TND" => Self::Tnd,
            "TOP" => Self::Top,
            "TRY" => Self::Try,
            "TTD" => Self::Ttd,
            "TWD" => Self::Twd,
            "TZS" => Self::Tzs,
            "UAH" => Self::Uah,
            "UGX" => Self::Ugx,
            "USD" => Self::Usd,
            "UYU" => Self::Uyu,
            "UZS" => Self::Uzs,
            "VES" => Self::Ves,
            "VND" => Self::Vnd,
            "VUV" => Self::Vuv,
            "WST" => Self::Wst,
            "XAF" => Self::Xaf,
            "XCD" => Self::Xcd,
            "XOF" => Self::Xof,
            "XPF" => Self::Xpf,
            "YER" => Self::Yer,
            "ZAR" => Self::Zar,
            "ZMW" => Self::Zmw,
            "ZWL" => Self::Zwl,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

impl fmt::Display for Currency {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl Serialize for Currency {
    fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
        serializer.serialize_str(self.as_str())
    }
}

impl<'de> Deserialize<'de> for Currency {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        String::deserialize(deserializer).map(|value| Self::from(value.as_str()))
    }
}

impl crate::request::QueryParamValue for Currency {
    fn encode(&self) -> String {
        self.to_string()
    }
}
